server.port: 8081
spring:
  application:
    name: event-processor
  cloud:
    stream:
      bindings:
        user:
          destination: user
          group: user-group
          contentType: 'application/json'
          consumer:
            durableSubscription: true
        friend:
          destination: friend
          group: friend-group
          contentType: 'application/json'
          consumer:
            durableSubscription: true
  data:
    neo4j:
      username: neo4j
      password: graphdb