language: java
jdk:
- openjdk11
services:
- docker
env:
  matrix:
  - DOCKER_COMPOSE_VERSION=1.23.2
  - secure: ijFq7uaOhIB1kJEw+tPWENYL0sxElibTvVxgnBwRXiBx9EQC21UxxCSCxxEAvjw2uSsjf9Py6hNaN1PoUKfc+k0l5PChodny+WcDMHpkFKqS2wOVQdauW/X9Aa6RNJU2SAbvCdOeWlXMdoI2ACD7ULnyZAQKwhz3QHclWHVEinFA8k3AF/YfMwQQEZShkqnLgf/W652aySetV2YXeGf4ygO7AX4yr9g/epIVi7xL6s06WeAklTiIYKDNr3+M9O5mySkxqh8Z8Dr/Sgh/x3WvgVm/6AHhVN+5psBXI6Hq/dmfGuTvwSrV/+5CmzRuLhdkMq3hs96ZJtbJQNLbF3AxA3Emhvxs8loW3T2R9YsK0W2/RkEGrVkudLFMRkvg3oodO/x9yrsoo5/kcXy8TwCc92wDfgHUKFUjq1MxXj57RFJ2T8PSC/zFSAgPtEifoaaxIwfe9UbOtjjQGhrkJjggSEu6etE4jcEe5nyoZlPP0tk+JFqIcxPSI6VOnz4vUoa2IiaGj8SAN//wFJ2ijmgbRayQcLv4skcTm+11KyhAsVOplPZAdNMSTU73n1d19By3jkVQaITkNxNOXGbIx9/3m0vki8LWdu/UrvJjwFllIx5QN9q8P6/SIQtiCLSq+NcaQYrMHnHAod1q3bT6wB5+VxeyElFT+74RP7ERdDk+WqM=
  - secure: UjXHGdTXWwAdwdEDYNkFfMRtrRGGMWYLGFfssiEZq0DFNo3RD/QKJKyJadH0Sk71D15mujI/k04ZxEU8nGD/VZtZuo4oePsISz+vTNvTPPV5F1YC67nzxpiUfZFpFGpgZzkbx1Dn1DKRgZDF+6XhpkJNei+HASLMVCCwEaO/bfIx7FBKlzTawIKNsCdkRnwGyLeZtMTwaFMZdHcFztYRh78KL+8vPInKmA6pMKz+PHQAc0fOt2DCoz/spBy3GzksXxgYMPj9mRhmGg4tinq47HyKwIwA9WxRViUhFoJvPERy0RD1P1TeqRVpU0MGMVS4l4MqrNhq5s21w/RFdg7VplRNWo3oIDS5VUBP8zdxCfYZLUhvvorfXsDdHDmJR8Hk7CAV4yh2jWjyWTsFyS6krjaJnefmKkeov5ldQktrciQL9ZEbnxk4Xf+XWXyK1Li0ABQz2gRWm0UiRoua0Z+Kx3sNwjEQYzxXgUfZPcXB5ztKXUzLTffAbHR1TMVabvvCkTt+nzEx6i2OVT1FfUmC1S4Lvc4VosZIOqZcBxJI8ZaJWGnGKsYEFlMJogT2B0P/ALy3QexfgXkJtp0WCBcFj1+2MmVkcTcCAv6MIH74GyJAyE2cfWY8LDNg4qMyIHEemcGmKhX+gvyOHThr2/JFIPt18BbOXn5ktYcC7cbQzlc=
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
