version: "3.3"

services:

  discovery-service:
    environment:
      SPRING_PROFILES_ACTIVE: docker
    image: kbastani/discovery-service:latest
    ports:
      - "8761:8761/tcp"

  edge-service:
    environment:
      SPRING_PROFILES_ACTIVE: docker
    image: kbastani/edge-service:latest
    ports:
      - "9000:9000/tcp"

  friend-service:
    environment:
      SPRING_PROFILES_ACTIVE: docker
    image: kbastani/friend-service:latest

  user-service:
    environment:
      SPRING_PROFILES_ACTIVE: docker
    image: kbastani/user-service:latest

  recommendation-service:
    environment:
      SPRING_PROFILES_ACTIVE: docker
    image: kbastani/recommendation-service:latest

  kafka:
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
    image: confluentinc/cp-kafka:latest
    ports:
      - "29092:29092/tcp"

  zookeeper:
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "32181:32181/tcp"

  neo4j:
    environment:
      NEO4J_AUTH: none
    image: neo4j:3.5.0
    ports:
      - "7474:7474/tcp"
      - "7687:7687/tcp"

  friend-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432/tcp"

  user-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432/tcp"

  adminer:
    image: adminer:latest
    ports:
      - "8080:9191"
