spring.profiles.active: development
server.port: 0
---
spring:
  profiles: development
  cloud:
    stream:
      bindings:
        output:
          destination: friend
          contentType: 'application/json'
---
spring:
  profiles: test
  cloud:
    stream:
      bindings:
        output:
          destination: friend
          contentType: 'application/json'