spring:
  profiles:
    active: development
  cloud:
    kubernetes:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
      - id: friend-service
        uri: lb://friend-service
        predicates:
        - name: Path
          args:
            pattern: "/friend/**"
        filters:
        - name: RewritePath
          args:
            regexp: "/friend/(?<remaining>.*)"
            replacement: "/${remaining}"
      - id: user-service
        uri: lb://user-service
        predicates:
        - name: Path
          args:
            pattern: "/user/**"
        filters:
        - name: RewritePath
          args:
            regexp: "/user/(?<remaining>.*)"
            replacement: "/${remaining}"
      - id: recommendation-service
        uri: lb://recommendation-service
        predicates:
        - name: Path
          args:
            pattern: "/recommendation/**"
        filters:
        - name: RewritePath
          args:
            regexp: "/recommendation/(?<remaining>.*)"
            replacement: "/${remaining}"
server:
  port: 9000
management:
  endpoint:
    gateway:
      enabled: true
---
spring:
  profiles: development
  cloud:
    kubernetes:
      enabled: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: kubernetes
  cloud:
    kubernetes:
      enabled: true
      discovery:
        enabled: true
      ribbon:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression: "'http://'+serviceId"
kubernetes.trust.certificates: true
management.endpoints.web.exposure.include: gateway,health
# disable eureka
ribbon.eureka.enabled: false
eureka.client.enabled: false
# kubernetes ribbon client requires a portName for each service
#friend-service.ribbon.portName: http
#user-service.ribbon.portName: http
#recommendation-service.ribbon.portName: http
---
spring:
  profiles: test
eureka:
  client:
    enabled: false
