spring:
  profiles:
    active: development
  application:
    name: edge-service
server:
  port: 9000
zuul:
  ignored-services: '*'
  routes:
    aggregate-service: /aggregate/**
    friend-service: /friend/**
    user-service: /user/**
---
spring:
  profiles: development
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
eureka:
  client:
    enabled: false