spring:
  profiles:
    active: development
  application:
    name: edge-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
      - id: FRIEND-SERVICE
        uri: lb://FRIEND-SERVICE
        predicates:
        - name: Path
          args:
            pattern: "/friend/**"
        filters:
        - name: RewritePath
          args:
            regexp: "/friend/(?<remaining>.*)"
            replacement: "/${remaining}"
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - name: Path
          args:
            pattern: "/user/**"
        filters:
        - name: RewritePath
          args:
            regexp: "/user/(?<remaining>.*)"
            replacement: "/${remaining}"
      - id: RECOMMENDATION-SERVICE
        uri: lb://RECOMMENDATION-SERVICE
        predicates:
        - name: Path
          args:
            pattern: "/recommendation/**"
        filters:
        - name: RewritePath
          args:
            regexp: "/recommendation/(?<remaining>.*)"
            replacement: "/${remaining}"
server:
  port: 9000
management:
  endpoint:
    gateway:
      enabled: true

---
spring:
  profiles: development
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management.endpoints.web.exposure.include: gateway
---
spring:
  profiles: docker
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
management.endpoints.web.exposure.include: gateway
---
spring:
  profiles: test
eureka:
  client:
    enabled: false