spring:
  application:
    name: user-service
  profiles:
    active: development
  cloud:
    stream:
      bindings:
        output:
          destination: user
          contentType: 'application/json'
server:
  port: 0
---
spring:
  profiles: development
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          defaultBrokerPort: 29092
          zkNodes: zookeeper
          defaultZkPort: 32181
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test