spring:
  profiles:
    active: development
  application:
    name: discovery-service
server:
  port: 8761
---
spring:
  profiles: development
eureka:
  instance:
    preferIpAddress: true
---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
---
spring:
  profiles: test
eureka.client.enabled: false