spring:
  application:
    name: aggregate-service
  profiles:
    active: development
  cloud:
    stream:
      bindings:
        user:
          destination: user
          group: user-group
          contentType: 'application/json'
          consumer:
            durableSubscription: true
        friend:
          destination: friend
          group: friend-group
          contentType: 'application/json'
          consumer:
            durableSubscription: true
server:
  port: 0
---
spring:
  profiles: development
  data:
    neo4j:
      uri: http://192.168.99.100:7474
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  data:
    neo4j:
      uri: http://neo4j:7474
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          defaultBrokerPort: 29092
          zkNodes: zookeeper
          defaultZkPort: 32181
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test